### ISSUE TITLE
how to train a model using my own videos

### ISSUE THREAD

**Issue by AlbertBJ** [NhatHoang2002/MotionMix#1]
Hi,I found that your training set comes from HumanML3D. How can I convert my videos into this format? thank you.

**Comment by NhatHoang2002** [comment]
Hi @AlbertBJ, since HumanML3D relies on AMASS data in SMPL+H format, you'll need to use a compatible mocap system to capture human motion and convert it to SMPL+H format. Here are general steps for training with your own videos in HumanML3D format:

**Step 1 - Capture Motion:** Use a suitable mocap pipeline (e.g., [VIBE](https://github.com/mkocabas/VIBE), [SMPLify-X](https://github.com/vchoutas/smplify-x), [EasyMocap](https://github.com/zju3dv/EasyMocap?tab=readme-ov-file) or a newer one) to capture motions from your videos in SMPL+H format.

**Step 2 - Process Data:** Run the processing code from [HumanML3D](https://github.com/EricGuo5513/HumanML3D?tab=readme-ov-file#extract-and-process-data).

**Step 3 - Train with Your Data**: Once you have your own data in HumanML3D format, you can train it alongside HumanML3D using our algorithm.

**Comment by AlbertBJ** [comment]
Okay, thank you very much, I'll try it first
